version: '3'
services:

  springboot-app:
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${SPRINGBOOT_APP_PORT}:8080"
    networks:
      - employee-mysql
    environment:
      SPRING_APPLICATION_JSON: '${SPRING_APPLICATION_JSON}'

  mysql-db:
    image: mysql:8
    restart: on-failure
    networks:
      - employee-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

networks:
  employee-mysql: